<?php if($page->items):?>

    <div class="row">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ФИО</th>
                <th>Примечание</th>
                <th>Телефоны</th>

                <th colspan="2">Действия</th>
            </tr>
            </thead>
            <tbody>
			<?php foreach ($page->items as $user): ?>
                <tr>
                    <td><?php echo $user->fio ?></td>
                    <td><?php echo $user->notes ?></td>
                    <td><?php
						foreach ($user->phones as $phone) {
							echo $phone->phone . "<br>";
						}
						?></td>
                    <td><?php echo $this->tag->linkTo(["users/edit/" . $user->id, "Редактировать", "class" => 'edit']); ?>
                        / <?php echo $this->tag->linkTo(["users/delete/" . $user->id, "Удалить", "class" => 'remove']); ?></td>
                </tr>
			<?php endforeach; ?>
            </tbody>
        </table>
        <!-- Modal for edit-->
        <div id="edit" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Редактировать контакт</h4>
                    </div>
                    <div class="modal-body editable">

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-2">
            <p class="pagination">
                Страница <?php echo $page->current, " из ", $page->total_pages ?>
            </p>
        </div>
        <div class="col-sm-10">
            <nav>
                <ul class="pagination">
                    <li><?php echo $this->tag->linkTo("users/", "Первая") ?></li>
                    <li><?php echo $this->tag->linkTo("users/?page=" . $page->before, "Предыдущая") ?></li>
                    <li><?php echo $this->tag->linkTo("users/?page=" . $page->next, "Следующая") ?></li>
                    <li><?php echo $this->tag->linkTo("users/?page=" . $page->last, "Последняя") ?></li>
                </ul>
            </nav>
        </div>
    </div>
<?php endif;?>